spring:
  application:
    name: lzafterservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lz
    username: root
    password: root
server:
  port: 1010
mybatis:
  type-aliases-package: com.lz.model.pojo
  mapper-locations: classpath:/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/